config/routes.rb
Rails.application.routes.draw do

  resources :stats
  resources :heroes, except: [:delete]
  get 'home', to: 'static#home'

end

app/models/hero.rb
class Hero < ActiveRecord::Base

  has_one :stat

end

app/models/stat.rb
class Stat < ActiveRecord::Base



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/heroes_controller.rb
class HeroesController < ApplicationController

  def index
    @heroes = Hero.all.sort_by{|x| x.faction}
    respond_to do |format|
      format.html {render :index}
      format.json {render json: @heroes, each_serializer: HeroIndexSerializer}
    end
  end

  def show
    @hero = Hero.find(params[:id])
    respond_to do |format|
      format.html {render :show}
      format.json {render json: @hero}
    end
  end

  def new
    @hero = Hero.new()
  end

  def create
    @hero = Hero.new(hero_params)
    @stat = Stat.new(stats_params["stats"])
    @hero.stat = @stat
    if @hero.save && @stat.save
      redirect_to hero_path(@hero)
    else
      render :new
    end
  end

  def edit
    @hero = Hero.find_by(id: params[:id])
  end

  def update
    @hero = Hero.find_by(id: params[:id])
    @stat = Stat.find_by(id: params[:id])
    @hero.stat = @stat
    if @hero.save && @stat.save
      redirect_to hero_path(@hero)
    else
      render :edit
    end

  end

  private

  def hero_params
    params.require(:hero).permit(:name, :faction, :role, :skills, :stats_id)
  end

  def stats_params
    params.require(:hero).permit(:stats => [:health, :attack, :armor, :speed])
  end

end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/heroes_helper.rb
module HeroesHelper
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/views/heroes/_form.html.erb
<% if @hero.errors.any? %>
  <ul>
    <% @hero.errors.full_messages.each do |message| %>
      <li><%= message %></li><br>
    <% end %>
  </ul>
<% end %>

<%= form_for @hero do |f| %>

  <h3>Hero Info</h3>

  <p><%= f.label :name %></p>
  <p><%= f.text_field :name %><p>
  <p><%= f.label :faction %></p>
  <p><%= f.text_field :faction %></p>
  <p><%= f.label :role %></p>
  <p><%= f.text_field :role %></p>
  <p><%= f.label :skills %></p>
  <p><%= f.number_field :skills %></p>

  <h3>Stats</h3>

  <%= f.fields_for :stats do |info| %>

    <p><%= info.label :health %></p>
    <p><%= info.number_field :health %></p>
    <p><%= info.label :attack %></p>
    <p><%= info.number_field :attack %></p>
    <p><%= info.label :armor %></p>
    <p><%= info.number_field :armor %></p>
    <p><%= info.label :speed %></p>
    <p><%= info.number_field :speed %></p>

  <% end %>

  <p><%= f.submit %></p>

<% end %>

app/views/heroes/edit.html.erb
<h1>Edit This Hero</h1>

<%= render 'form' %>

<br>

<%= link_to "Return Without Editing", hero_path(@hero) %>

app/views/heroes/index.html.erb
<h2>All Heroes</h2>

<% @heroes.each do |hero| %>
  <h3><%= link_to "#{hero.name}", hero_path(hero) %></h3>
  Faction: <%= hero.faction %> <br>
  Role: <%= hero.role %>  <br>
  Skills: <%= hero.skills %> <br>
  <button class="js-more" data-id="<%= hero.id %>">More Info</button>
  <ul id="heroes-<%= hero.id %>-stats">
  </ul>
<% end %>


<script type="text/javascript" charset="utf-8">
$(function() {
  $(".js-more").on("click", function() {
    var id = $(this).data("id");
    $.get("/heroes/" + id + ".json", function(data) {
      var stats = data.stat
      var statsList = ""
      for (var i in stats){
        statsList += '<li class="js-stat" data-id="' + data.id + '">' + i + ': ' + stats[i] + '</li>';
      }
      $("#heroes-" + id + "-stats").html(statsList);
    });
  });
});
</script>


<%= link_to "Create a New Hero", new_hero_path %>

app/views/heroes/new.html.erb
<h1>Create a New Hero</h1>

<%= render 'form' %>

<br>

<%= link_to "Return to All Heroes Without Creating a New One", heroes_path %>

app/views/heroes/show.html.erb
<h1> <%= @hero.name %> </h1>

Faction: <%= @hero.faction %> <br>
Role: <%= @hero.role %>  <br>
<h3> Stats </h3>
Health: <%= @hero.stat.health %><br>
Attack: <%= @hero.stat.attack %><br>
Armor: <%= @hero.stat.armor %><br>
Speed: <%= @hero.stat.speed %><br>

Skills: <%= @hero.skills %> <br>
<br>
<%= link_to "Edit This Hero", edit_hero_path(@hero) %><br>
<%= link_to "Return to All Heroes", heroes_path %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsLayoutsAndTemplatesLab</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1>Flatiron Widgets: Admin</h1>


<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsLayoutsAndTemplatesLab</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1>Idle Heroes</h1>



<%= yield %>

</body>
</html>

app/views/layouts/order_administration.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsLayoutsAndTemplatesLab</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1>Flatiron Widgets: Open Orders</h1>


<%= yield %>

</body>
</html>